//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloAdministracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaPedido
    {
        public int PedidoID { get; set; }
        public int LineaPedidoID { get; set; }
        public int PlatilloID { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Platillo Platillo { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
