//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloAdministracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillo
    {
        public int PlatilloID { get; set; }
        public string Nombre { get; set; }
        public string DescPlatillo { get; set; }
        public decimal Precio { get; set; }
        public bool Inhabilitado { get; set; }
        public byte[] Foto { get; set; }
    }
}
